using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ApiEnvio.Models
{
    public class Users
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string Id { get; set; }
        public string Nome { get; set; }
        public string Cpf { get; set; } 
        public string Senha { get; set; }

    }
}
